CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,

  avatar_url TEXT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',

  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  verification_code VARCHAR(10) NULL,

  plan_type VARCHAR(50) NULL,
  plan_start DATETIME NULL,
  plan_end DATETIME NULL,
  plan_active BOOLEAN NOT NULL DEFAULT FALSE,

  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  blocked_at DATETIME NULL,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);